### ISSUE TITLE
Qlogin not working

### ISSUE THREAD

**Issue by celiademarchi** [c3nl-neuraldynamics/c3nl_cluster#62]
Hi,
qlogin isn't working. I haven't (Sara either) been able to submit anything since last week. This is the error message:
[cdemarch@brodmann23d DTI]$ qlogin
srun: error: Task launch for 1466614.0 failed on node compute-0-1: Job credential expired
srun: error: Application launch failed: Job credential expired
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: Timed out waiting for job step to complete

**Comment by petehellyer** [comment]
Eyal, I suspect this is because the clocks are out of sync. Would you be able to sync NTP across the cluster? I’d do it myself, but for reasons I’m lost on, I can’t VPN into the college at the moment….

P

On 19 Dec 2017, at 10:53, celiademarchi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
qlogin isn't working. I haven't (Sara either) been able to submit anything since last week. This is the error message:
[cdemarch@brodmann23d DTI]$ qlogin
srun: error: Task launch for 1466614.0 failed on node compute-0-1: Job credential expired
srun: error: Application launch failed: Job credential expired
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: Timed out waiting for job step to complete

**Comment by petehellyer** [comment]
Yes, will do.

**Comment by celiademarchi** [comment]
Thank you, I know Neil was having this same issue too. Thanks for sorting and hope you have a lovely Christmas.


Kind Regards,


Célia


Dr Célia Demarchi

Clinical Psychologist
The Computational, Cognitive and Clinical Neuroimaging Laboratory (C3NL): Imperial College London
Neuropsychology Service: Great Ormond Street Hospital for Children NHS Foundation Trust


________________________________

**Comment by petehellyer** [comment]
I think our ntp setup is wrong
Running the following produces the same error
[root@brodmann23d eyalsoreq]# ssh root@compute-2-3 ntpdate -s 10.2.1.1
[root@brodmann23d eyalsoreq]# srun --nodelist=compute-2-3 sleep 6
srun: error: Task launch for 1472878.0 failed on node compute-2-3: Job
credential expired
srun: error: Application launch failed: Job credential expired
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: Timed out waiting for job step to complete

**Comment by sdesimoni** [comment]
Hello! Just to let you know the qlogin command is still giving the same error that Célia posted before xmas.....

**Comment by petehellyer** [comment]
fixed
